# make sure to account for upper/lower case - the game shouldn't differentiate
# also the players can't guess punctuation, so make sure that's already given to them
# and displayed in the phrase on screen
phrases = [
    "A blessing in disguise",
    "A dime a dozen",
    "A piece of cake",
    "An arm and a leg",
    "Break the ice",
    "Bite the bullet",
    "Best of both worlds",
    "Burn the midnight oil",
    "Call it a day",
    "Cut to the chase",
    "Don't count your chickens before they hatch",
    "Every cloud has a silver lining",
    "Fit as a fiddle",
    "Go the extra mile",
    "Hit the nail on the head",
    "In the nick of time",
    "It takes two to tango",
    "Jump on the bandwagon",
    "Keep your chin up",
    "Kill two birds with one stone",
    "Let the cat out of the bag",
    "Live and learn",
    "Look before you leap",
    "Make a long story short",
    "Miss the boat",
    "No pain, no gain",
    "Once in a blue moon",
    "Out of the frying pan and into the fire",
    "Piece of cake",
    "Pull someone's leg",
    "Raining cats and dogs",
    "See eye to eye",
    "Speak of the devil",
    "The ball is in your court",
    "The best of both worlds",
    "The elephant in the room",
    "The last straw",
    "The tip of the iceberg",
    "Throw in the towel",
    "Under the weather",
    "Up in the air",
    "When pigs fly",
    "Wrap your head around something",
    "You can say that again",
    "Your guess is as good as mine",
    "A penny for your thoughts",
    "Add insult to injury",
    "All ears",
    "Barking up the wrong tree",
    "Beat around the bush",
    "Better late than never",
    "Bite off more than you can chew",
    "Break a leg",
    "Burst your bubble",
    "Close but no cigar",
    "Cut corners",
    "Cut someone some slack",
    "Easy does it",
    "Get out of hand",
    "Get something off your chest",
    "Give someone the cold shoulder",
    "Go back to the drawing board",
    "Hang in there",
    "Hit the sack",
    "Ignorance is bliss",
    "It's not rocket science",
    "Jump the gun",
    "Let sleeping dogs lie",
    "Let the chips fall where they may",
    "Make a mountain out of a molehill",
    "No use crying over spilled milk",
    "On the ball",
    "Once bitten, twice shy",
    "Pull yourself together",
    "Put all your eggs in one basket",
    "Put the pedal to the metal",
    "Sit on the fence",
    "Spill the beans",
    "Steal someone's thunder",
    "Take it with a grain of salt",
    "The whole nine yards",
    "Through thick and thin",
    "To make matters worse",
    "Two peas in a pod",
    "Under the weather",
    "We see eye to eye",
    "You can't judge a book by its cover",
    "A picture is worth a thousand words",
    "Actions speak louder than words",
    "All good things must come to an end",
    "Better safe than sorry",
    "Curiosity killed the cat",
    "Don't put all your eggs in one basket",
    "Every dog has its day",
    "Great minds think alike",
    "Haste makes waste",
    "Honesty is the best policy",
    "Keep your friends close and your enemies closer",
    "Laughter is the best medicine",
    "Like father, like son",
    "Practice makes perfect",
    "The early bird catches the worm",
    "There's no place like home",
    "Time flies when you're having fun",
    "Too good to be true",
    "You can't have your cake and eat it too"
]
