# it should be safe to assume these are purely alphabetical
# (assume no punctuation, but don't assume lowercase)
words = [
    "abruptly", "absurd", "abyss", "actor", "affix", "airplane", "arch", "artist",
    "askew", "athlete", "awkward", "axiom", "azure", "bagpipes", "ball", "banana",
    "bandwagon", "banjo", "bayou", "beekeeper", "bicycle", "bikini", "blitz",
    "blizzard", "boggle", "book", "bookworm", "bottle", "boxcar", "boxful",
    "bread", "buckaroo", "buffalo", "buffoon", "buxom", "buzzard", "buzzing",
    "buzzwords", "camera", "caliph", "car", "cat", "circle", "cloud", "cobweb",
    "cockiness", "computer", "croquet", "crypt", "curacao", "cup", "cycle", "dance",
    "desk", "dish", "doctor", "dog", "dolphin", "door", "dragon", "duplex",
    "dwarves", "ear", "earring", "egg", "elephant", "embezzle", "engineer", "energy",
    "equip", "espionage", "exodus", "family", "fan", "feather", "fire", "fish",
    "fishhook", "fixable", "fjord", "flapjack", "flower", "fluffiness", "flyby",
    "forest", "foxglove", "frazzled", "frizzled", "fuchsia", "funny", "gabby",
    "galaxy", "galvanize", "game", "garden", "gazebo", "giraffe", "gizmo", "glowworm",
    "glyph", "gnarly", "gnostic", "goat", "gold", "gossip", "grogginess", "guitar",
    "haiku", "haphazard", "hat", "heart", "hill", "home", "horse", "hospital",
    "house", "hyphen", "ice", "icebox", "idea", "igloo", "injury", "ink", "insect",
    "island", "ivory", "ivy", "jackpot", "jacket", "jam", "jaundice", "jawbreaker",
    "jaywalk", "jazz", "jazziest", "jazzy", "jeans", "jelly", "jewel", "jigsaw",
    "jinx", "jockey", "jogging", "joking", "jovial", "joyful", "juicy", "jukebox",
    "jungle", "junior", "jumbo", "kangaroo", "kayak", "kazoo", "key", "keyhole",
    "khaki", "kilobyte", "king", "kite", "kiwifruit", "klutz", "koala", "kitchen",
    "knapsack", "lamp", "lake", "larynx", "leaf", "lemon", "lengths", "library",
    "lion", "lucky", "luxury", "lymph", "matrix", "megahertz", "microwave", "mnemonic",
    "moon", "mountain", "movie", "mystify", "nature", "nest", "night", "nightclub",
    "nowadays", "numbskull", "nurse", "nymph", "oasis", "ocean", "octopus", "onion",
    "orange", "ovary", "oxidize", "oxygen", "owl", "painting", "pajama", "park",
    "peekaboo", "pencil", "phlegm", "piano", "pizza", "pixel", "pizazz", "plant",
    "pillow", "polka", "puppy", "puzzling", "queen", "queue", "quick", "quicksand",
    "quilt", "quips", "quixotic", "quiz", "quizzes", "quorum", "rabbit", "rain",
    "rainbow", "question", "rhubarb", "rhythm", "rickshaw", "river", "road",
    "robot", "rose", "scratch", "school", "ship", "singer", "sky", "snazzy",
    "song", "sphinx", "squirrel", "squawk", "staff", "star", "strength", "strengths",
    "stretch", "stronghold", "stymied", "subway", "sun", "swivel", "syndrome",
    "teacher", "telephone", "thriftless", "tiger", "turtle", "umbrella", "unicorn",
    "unknown", "universe", "unworthy", "unzip", "uptown", "vacation", "valley",
    "vampire", "vase", "vehicle", "violin", "vixen", "vodka", "voodoo", "vortex",
    "voyeurism", "walkway", "wall", "waltz", "wave", "water", "waxy", "whale",
    "whisper", "whiskey", "whizzing", "whomever", "wimpy", "wind", "window", "witchcraft",
    "wizard", "woozy", "wristwatch", "wyvern", "xenon", "xenophobia", "xylophone",
    "xylophonist", "yacht", "yard", "yarn", "yeti", "yippee", "yogurt", "yoked",
    "youth", "youthful", "yummy", "zephyr", "zigzag", "zilch", "zinc", "zipper",
    "zodiac", "zombie", "zoo", "zucchini"
]
